[versions]
# Project
jambalaya-checks = "0.7.0-SNAPSHOT"
jambalaya-checks-jooq = "0.7.0-SNAPSHOT"
jambalaya-graphql = "0.7.0-SNAPSHOT"
jambalaya-graphql-apollo = "0.8.0-SNAPSHOT"
jambalaya-graphql-jooq = "0.7.0-SNAPSHOT"
jambalaya-jsr310 = "0.7.0-SNAPSHOT"
jambalaya-junit-opentelemetry = "0.5.0-SNAPSHOT"
jambalaya-kotlin-test = "0.7.0-SNAPSHOT"
jambalaya-mapstruct = "0.6.0-SNAPSHOT"
jambalaya-mapstruct-processor = "0.6.0-SNAPSHOT"
jambalaya-micronaut-graphql = "0.7.0-SNAPSHOT"
jambalaya-micronaut-mapstruct-protobuf = "0.6.0-SNAPSHOT"
jambalaya-opentelemetry = "0.5.0-SNAPSHOT"
jambalaya-protobuf = "0.8.0-SNAPSHOT"
jambalaya-seo = "0.7.0-SNAPSHOT"
jambalaya-tenancy = "0.7.0-SNAPSHOT"
jambalaya-tenancy-flyway = "0.4.0-SNAPSHOT"
jambalaya-tenancy-grpc-api = "0.4.0-SNAPSHOT"
jambalaya-tenancy-jooq = "0.4.0-SNAPSHOT"
jambalaya-tenancy-junit = "0.4.0-SNAPSHOT"

# Libraries
apollo = "3.0.0"
common-protos = "2.7.0"
graphql-data-loader = "3.1.1"
grpc = "1.39.0"
guava = "31.0.1-jre"
mapstruct = "1.5.0.Beta2"
micronaut = "3.2.3"
okhttp = "4.9.3"
opentelemetry = "1.9.1"
opentelemetry-alpha = "1.9.1-alpha"
protobuf = "3.17.2"
slugify = "2.5"

[libraries]
# BOMs
boms-grpc = { module = "io.grpc:grpc-bom", version.ref = "grpc" }
boms-micronaut = { module = "io.micronaut:micronaut-bom", version.ref = "micronaut" }
boms-opentelemetry = { module = "io.opentelemetry:opentelemetry-bom", version.ref = "opentelemetry" }

# Libraries
apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
java-dataloader = { module = "com.graphql-java:java-dataloader", version.ref = "graphql-data-loader" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
okhttp-urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp" }
opentelemetry-bom-alpha = { module = "io.opentelemetry:opentelemetry-bom-alpha", version.ref = "opentelemetry-alpha" }
proto-google-common-protos = { module = "com.google.api.grpc:proto-google-common-protos", version.ref = "common-protos" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protoc-gen-grpc-java = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc" }
slugify = { module = "com.github.slugify:slugify", version.ref = "slugify" }
