[versions]
# Project
jambalaya-checks = "0.14.0"
jambalaya-checks-jooq = "0.14.0"
jambalaya-graphql = "0.14.0"
jambalaya-graphql-apollo = "0.15.0"
jambalaya-graphql-jooq = "0.14.0"
jambalaya-jsr310 = "0.14.0"
jambalaya-junit-opentelemetry = "0.15.0"
jambalaya-kotlin-test = "0.15.0"
jambalaya-mapstruct = "0.13.0"
jambalaya-mapstruct-processor = "0.13.0"
jambalaya-micronaut-graphql = "0.14.0"
jambalaya-micronaut-mapstruct-protobuf = "0.15.0"
jambalaya-opentelemetry = "0.13.0"
jambalaya-protobuf = "0.16.0"
jambalaya-seo = "0.14.0"
jambalaya-tenancy = "0.15.0"
jambalaya-tenancy-flyway = "0.12.0"
jambalaya-tenancy-grpc-api = "0.12.0"
jambalaya-tenancy-jooq = "0.12.0"
jambalaya-tenancy-junit = "0.12.0"
jambalaya-tenancy-spock = "0.12.0"

# Libraries
apollo = "4.4.1"
common-protos = "2.65.1"
graphql-data-loader = "6.0.0"
grpc = "1.79.0"
guava = "33.5.0-jre"
mapstruct = "1.6.3"
micronaut = "4.10.14"
micronaut-graphql = "4.8.0"
okhttp = "5.3.2"
protobuf = "3.25.8"
slugify = "3.0.7"
error-prone = "2.47.0"
icu4j = "78.2"
spock = "2.3-groovy-4.0"
jooq = "3.20.11"
opentelemetry = "1.59.0"
opentelemetry-semconv = "1.39.0"
opentelemetry-semconv-alpha = "1.37.0-alpha"
jspecify = "1.0.0"
junit = "6.0.2"
flyway = "11.20.3"
slf4j = "2.0.17"

[libraries]
# Libraries
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
java-dataloader = { module = "com.graphql-java:java-dataloader", version.ref = "graphql-data-loader" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
okhttp-urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp" }
proto-google-common-protos = { module = "com.google.api.grpc:proto-google-common-protos", version.ref = "common-protos" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protoc-gen-grpc-java = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc" }
slugify = { module = "com.github.slugify:slugify", version.ref = "slugify" }
tomcat-annotations-api = { module = "org.apache.tomcat:annotations-api", version = "6.0.53" }
error-prone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "error-prone" }
icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu4j" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
micronaut-inject-java = { module = "io.micronaut:micronaut-inject-java", version.ref = "micronaut" }
micronaut-graphql = { module = "io.micronaut.graphql:micronaut-graphql", version.ref = "micronaut-graphql" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry" }
opentelemetry-semconv = { module = "io.opentelemetry.semconv:opentelemetry-semconv", version.ref = "opentelemetry-semconv" }
opentelemetry-semconv-incubating = { module = "io.opentelemetry.semconv:opentelemetry-semconv-incubating", version.ref = "opentelemetry-semconv-alpha" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
