[versions]
# Project
jambalaya-checks = "0.7.2"
jambalaya-checks-jooq = "0.7.2"
jambalaya-graphql = "0.7.2"
jambalaya-graphql-apollo = "0.8.3"
jambalaya-graphql-jooq = "0.7.2"
jambalaya-jsr310 = "0.7.2"
jambalaya-junit-opentelemetry = "0.5.2"
jambalaya-kotlin-test = "0.7.2"
jambalaya-mapstruct = "0.6.2"
jambalaya-mapstruct-processor = "0.6.2"
jambalaya-micronaut-graphql = "0.7.2"
jambalaya-micronaut-mapstruct-protobuf = "0.6.2"
jambalaya-opentelemetry = "0.5.2"
jambalaya-protobuf = "0.8.2"
jambalaya-seo = "0.7.2"
jambalaya-tenancy = "0.7.2"
jambalaya-tenancy-flyway = "0.4.2"
jambalaya-tenancy-grpc-api = "0.4.3"
jambalaya-tenancy-jooq = "0.4.2"
jambalaya-tenancy-junit = "0.4.2"

# Libraries
apollo = "3.6.2"
common-protos = "2.9.6"
graphql-data-loader = "3.2.0"
grpc = "1.50.1"
guava = "31.1-jre"
mapstruct = "1.5.3.Final"
micronaut = "3.7.2"
okhttp = "4.10.0"
opentelemetry = "1.19.0"
opentelemetry-alpha = "1.11.0-alpha"
protobuf = "3.21.8"
slugify = "3.0.2"
error-prone = "2.16"
icu4j = "72.1"

[libraries]
# BOMs
boms-grpc = { module = "io.grpc:grpc-bom", version.ref = "grpc" }
boms-micronaut = { module = "io.micronaut:micronaut-bom", version.ref = "micronaut" }
boms-opentelemetry = { module = "io.opentelemetry:opentelemetry-bom", version.ref = "opentelemetry" }

# Libraries
apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
apollo-rx3-support = { module = "com.apollographql.apollo3:apollo-rx3-support", version.ref = "apollo" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
java-dataloader = { module = "com.graphql-java:java-dataloader", version.ref = "graphql-data-loader" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
okhttp-urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp" }
opentelemetry-bom-alpha = { module = "io.opentelemetry:opentelemetry-bom-alpha", version.ref = "opentelemetry-alpha" }
proto-google-common-protos = { module = "com.google.api.grpc:proto-google-common-protos", version.ref = "common-protos" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protoc-gen-grpc-java = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc" }
slugify = { module = "com.github.slugify:slugify", version.ref = "slugify" }
tomcat-annotations-api = { module = "org.apache.tomcat:annotations-api", version = "6.0.53" }
error-prone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "error-prone" }
icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu4j" }
